### ISSUE TITLE
Should one base finite group theory on fintype or finset or neither?

### ISSUE THREAD

**Issue by htzh** [leanprover/tutorial#101]
There seems to be at least three choices:
1. Base off unrestricted type and standard sets. Every finite group is a subgroup. One has to get to finiteness and cardinality somehow using a bijection.
2. Base off fintype and standard sets. One gets a whole group but expanding it may be troublesome?
3. Base off unrestricted type and finset. Maybe same as 1 but use the finset to establish finiteness.

**Comment by avigad** [comment]
Coincidentally, I have been thinking about this a lot over the last few days. We want to have both constructive and classical theories of finite groups, and constructive and classical theories about arbitrary groups, and they should all fit together reasonably and avoid duplication as much as possible.

Some duplication is unavoidable. Many set-theoretic operations are mirrored on finset, but from a computational point of view, the representation of sets and finsets are very different. 

Right now, here is how I think we should proceed. I will talk about sets and finite sets first, and then groups and finite groups.

Constructively, we can use finset for dealing with finite sets, and set for dealing with arbitrary sets. A finset can be cast to a set. Things like cardinality, big operations, etc. are based on finsets.

Classically, we can define a predicate "finite" on sets. There are many equivalent ways to define it; one way is to say that a set s is finite if it there exists a finset that is cast to it, i.e. a finset with the same elements. Classically, if s is finite, we can cast it back to a finset. That way, classically, we can define cardinality and big operations on finite sets.

We would like to have a theory of groups. Along the lines of the library implemented in SSReflect, what we really want is a theory of subgroups of a group. In other words, generally, we will have one big group GG, and lots of subgroups G, H, K, and also subsets A, B, C of the carrier of GG. We will define operations on those, like G intersect H and GH, and cosets, etc.

We should have a general theory of groups based on sets. In other words, we define cosets, subgroups, and operations on these in terms of sets, and prove the usual theorems about them. (There will be both constructive and classical parts of this theory.)

We should also have operations defined on finsets, i.e. cosets that are finsets, subgroups based on finsets, etc., with all the usual operations. Many definitions will parallel the ones for sets, but I don't see any good way around that. Leo and I have discussed some possibilities for unifying these, but they seem forced and inconvenient. As I said, computationally sets and finsets are very different, and constructively they are implemented by different "computer programs".

We can prove, however, that the finset operations implement the set operations, with translation principles like

  to_set (finset.inter a b) = set.inter (to_set a) (to_set b)

It should be routine to derive these, which say that the finset operations implement the corresponding operations on sets. Then many facts about finite sets and finite groups will follow from the more general ones for sets and groups. (We will eventually have automation like the simplifier that will make the transfer easier.)

This approach will allow us to deal with arbitrary groups, arbitrary subgroups of an arbitrary subgroups of an arbitrary group, and finite subgroups of an arbitrary group. If you want to restrict attention to finite group theory, then the underlying type of the large group can be a fintype. In that case, the two theories collapse: any arbitrary subset of a fintype is a finset. So I think either version will work for finite group theory.

To summarize: I think we want all this:
(1) A theory of cosets, subgroups, etc. of a group, based on set.
(2) A theory of finite cosets, finite subgroups, etc. of a group, based on finset.
(3) Theorems relating the finite objects and constructions with the general ones. 

For finite group theory, we can take the underlying type of the large group to be a type, and then use either approach. (The fact that the underlying type is a fintype will imply that the approaches are equivalent.)

Hintao, if you would like to work on any aspect of this, I would be happy to coordinate with you. My plan this week is to work on powers and finite sums and products so that we will have these things in algebraic structures, as well as on nat, int, rat, etc. But I would also like to do more work on finset and set, so if you let me know what you want to do, I will do my best to help.

(I guess the short answer to your question is that either approach -- based on sets or finsets -- sounds good to me.)

**Comment by leodemoura** [comment]
Dear Hintao, 

Thanks for trying Lean, and providing valuable feedback. 
This is very helpful for us since Lean is a new system.
I'd like to emphasize that Lean is an open source project, and contributions are very welcome.
There are many ways to contribute: finding problems, fixing typos, asking questions, implementing examples, writing documentation, implementing the support libraries (standard and HoTT), and implementing Lean itself. All of them are valuable.
Sorry for posting this message here, but your github account does not have an email associated with it.
 Could you say a few words about your interests and plans?
If you prefer, feel free to send an email to Jeremy and me.

Best wishes,
Leo

**Comment by htzh** [comment]
@avigad, thanks for sharing your thoughts on the subject. You give me a lot of food for thought and it will take me while to digest it all.
> if you would like to work on any aspect of this, I would be happy to coordinate with you. My plan this week is to work on powers and finite sums and products so that we will have these things in algebraic structures, as well as on nat, int, rat, etc. But I would also like to do more work on finset and set, so if you let me know what you want to do, I will do my best to help.

I would like to first prove Sylow theorems using Lean. First I need to get to Lagrange, then I would like to take the route of Orbit Stabilizer theorem and then Cauchy. I am working on cosets and subgroups based on sets and that feels fairly comfortable so far. I would like to first prove composition and equivalence lemmas at the coset/subgroup level and then use "point-free" equational reasoning as much as I can. The "point-free" reasoning will then hopefully be less dependent on the representation of the underlying structures.

To get to Lagrange, I have so far done the following:

1. Define cosets as images in a semigroup. Prove image compose therefore cosets compose (in the sense defined below).

2. Redefine cosets using inverse 
  ```definition glcoset a (H : set A) : set A := λ x, H (a⁻¹ * x)``` . 
  Prove equivalence to 1. Define operators:
  ```infixr `∘>`:55 := glcoset -- stronger than = (50), weaker than * (70)```
  Obtain composition:
  ```a ∘> b ∘> H = a*b ∘> H```

3. Define subgroups:
  ```
definition subgroup.mul_closed H := ∀ x y, (x ∈ H ∧ y ∈ H) → x * y ∈ H
definition subgroup.has_inv H := ∀ a, a ∈ H → a⁻¹ ∈ H
definition subgroup H := H 1 ∧ subgroup.mul_closed H ∧ subgroup.has_inv H
```
subgroup should be a structure but I can for now separate out the definition axioms as lemmas and interface to the lemmas so that the proofs can be less dependent on how subgroup is implemented.

4. Prove coset relationship as equivalence. Establish bijection among cosets of a subgroup. (almost done)

From here on I will need to get to finiteness and cardinalities. I was looking through the library and trying to get a sense of where it is leaning towards, which led to the opening question.

I will check out @soonhokong's fix to the project mode. If it works I will reorg my work so far into a project structure and clean up a bit and put it on Github.

**Comment by htzh** [comment]
In Chapter 8 of the tutorial it is stated that:
>Lean imposes the restriction that the source and target families have to be families of inductive types, as defined in Chapter Inductive Types. Note that these include parameterized structures, as discussed in the next chapter. Because inductive types are atomic — they do not unfold, definitionally, to other expressions — this reduces ambiguity and makes it easier for Lean's elaborator to determine when to consider a coercion. This restriction turns out to be mild in practice: most natural sources and targets for coercions are defined as inductive types, and any type T can be "wrapped" as an inductive type, by writing inductive foo (T : Type) := mk : T → foo. 
 
Does this mean that I can't coerce to set unless I wrap set in a structure? I was hoping that I can package up the subgroup in a structure that includes the underlying set and have it coerced to set automatically when set is expected.

**Comment by leodemoura** [comment]
> Does this mean that I can't coerce to set unless I wrap set in a structure? I was hoping that I can package up the subgroup in a structure that includes the underlying set and have it coerced to set automatically when set is expected.

This restriction will be remove as soon as we close the following issue:
https://github.com/leanprover/lean/issues/547

**Comment by htzh** [comment]
> Sorry for posting this message here, but your github account does not have an email associated with it.
Could you say a few words about your interests and plans?
If you prefer, feel free to send an email to Jeremy and me.

Dear Leo,
Just in case my email did not make through your spam filter, I did PM you and @avigad earlier. You should have my email address now. Let me know if you need more information.
