### ISSUE TITLE
Feature request : allow printing in console

### ISSUE THREAD

**Issue by artella-coding** [leanprover/tutorial#103]
Hi, if I paste the following code 

    import data.nat
    open nat

    eval 2 + 3

into the console at https://leanprover.github.io/tutorial/index.html and click the compile button, nothing is printed out. I just get : 

    -- Processing...
    -- Saved at cookie.
    -- Done(0.784sec)

Would it be possible to have the results of `eval` printed out in the console? Thanks

**Comment by avigad** [comment]
When you click the compile button, you should see a small "i" appear next to the line number for the eval. If you hover over that "I", you can see the output.

Is that sufficient for you?

**Comment by artella-coding** [comment]
@avigad Fantastic thanks, yes that is good enough for me.

**Comment by leodemoura** [comment]
BTW, if the output is big, then "i" hover text is not very useful.
The problem is that the "balloon" does not fit in the screen. 
This is recurrent issue when I'm making demos :-(
Here is a simple problematic example
```lean
import data.vector
print definition vector.map2
```

**Comment by artella-coding** [comment]
@avigad Hi, reopening the feature request following the comment by @leodemoura . Maybe an alternative would be to have the "i" output scrollable. Thanks

**Comment by soonhokong** [comment]
I think we need to have a setting pane (with an icon something like [this](https://thenounproject.com/term/setting/102532)) which allows us to set options. It should include at least the two things (and more):

 - Memory Size : int (64MB is default)
 - Output to Console : bool

We should save the changes in the cookie not to repeat setting things up. I will implement them when I have some time. Please feel free to add more options to have.

---

@leodemoura's example is pretty big and I'm not sure what is a good way to show this. Scrollable div might provide a bad UX because the editor itself is also scrollable and the two might interfere. I'll think about it more. Any suggestion is welcome of course.

**Comment by artella-coding** [comment]
@soonhokong Hi, that sounds like an excellent idea. Thanks

**Comment by artella-coding** [comment]
@soonhokong An additional option that might be useful : word wrap (or alternatively horizontal scroll on command window)

For me `check (λ(Q R S : Type) (v : R → S) (u : Q → R) (x : Q), v (u x)) A B C g f a` goes off the screen

Thanks

**Comment by htzh** [comment]
Another thing about only showing output in a floating "balloon" is that it is hard (impossible?) to copy and paste from it.

**Comment by soonhokong** [comment]
Now there is a setting pane where you can set this as an option.
