### ISSUE TITLE
unexpected behavior from "print" command

### ISSUE THREAD

**Issue by avigad** [leanprover/tutorial#117]
In the online tutorial, the following:

``` lean
theorem foo (p : Prop) : p → p :=
λH, H

print foo
```

yields the following information:

```
information:print result:
theorem foo : ∀ (p : Prop), p → p
is_typeof
```

What is the spurious `is_typeof`?

Also, should the `reveal` command work in the tutorial? A user reports that on Firefox, he gets "unknown identifier 'reveal'". When I do it, "reveal" is syntax highlighted, but I get "error: command expected".

**Comment by avigad** [comment]
Other strange things are going on. In emacs, `print not.intro` yields
``` lean
theorem not.intro : ∀ {a : Prop}, (a → false) → ¬a :=
λ (a : Prop) (H : a → false), H
```
But in the tutorial, we get
```
information:print result:
axiom not.intro : ∀ {a : Prop}, (a → false) → ¬a
```

**Comment by fpvandoorn** [comment]
It seems the tutorial is using and old version of Lean + the Lean library. The `is_typeof` is explained if it isn't updated after this commit: https://github.com/leanprover/lean/commit/8056f326d7b32e7f869648e8a9f227e1fa82a072

The fact that the tutorial prints `not.intro` as `axiom` is explained here: https://github.com/leanprover/lean/issues/576#issuecomment-100399156:

> For the record, we also rely on `opaque` theorems when we generate `lean.js` (web version). To save space, we discard the proof of all theorems in the web version. If we execute
```
print axioms
```
on the web version, we get a huge list of "axioms".

Although I agree that the fact that it prints that `not.intro` is an axiom is not nice. Can we still print the theorems in the web version as theorems, and not as axioms? Maybe we can replace the proof by `sorry`, instead of discarding it? Or maybe make a web-version only version of `sorry`, which is called `proof_discarded` or `proof_hidden`. Then `print not.intro` will show
```
theorem not.intro : ∀ {a : Prop}, (a → false) → ¬a :=
proof_discarded
```

**Comment by leodemoura** [comment]
@fpvandoorn The following commit addresses the `print` issue. I will update the web version today.
https://github.com/leanprover/lean/commit/8a85e4ee875b603faa0293fc58a7cef0934c6a16
Example
```lean
open nat
theorem simple (a : nat) : a ≥ 0 :=
zero_le a
print simple
```
produces
```
theorem simple : ∀ (a : ℕ), a ≥ 0
'simple' is still in the theorem queue, use command 'reveal simple' to access its definition.
```

**Comment by fpvandoorn** [comment]
Does that commit also make the output better for theorems proven in the standard library? So what will be output of `print not.intro` be?

**Comment by leodemoura** [comment]
> Does that commit also make the output better for theorems proven in the standard library? So what will be output of print not.intro be?

In the web version, we discard the proofs of all theorems to save space. 
We should produce a better message in this case. Something like:
```
theorem not.intro : ∀ {a : Prop}, (a → false) → ¬a
In the web interface, the definition of theorems is discarded to save memory. 
Use the native lean binary to access the definition.
```

**Comment by leodemoura** [comment]
Another option is to have a flag whether we say whether the theorems should be discarded or not.

**Comment by fpvandoorn** [comment]
> ```
theorem not.intro : ∀ {a : Prop}, (a → false) → ¬a
In the web interface, the definition of theorems is discarded to save memory. 
Use the native lean binary to access the definition.
```

I think such a message would be good.

**Comment by avigad** [comment]
The issue is not causing problems in Lean 2.
