### ISSUE TITLE
use of theories.number_theory.primes in tutorial

### ISSUE THREAD

**Issue by soonhokong** [leanprover/tutorial#138]
@leodemoura and @avigad, we've decided not to include `theories` directory in library to reduce the size of `lean.js`. However, at the end of [chapter 4](https://github.com/leanprover/tutorial/blob/master/04_Quantifiers_and_Equality.org), we're using `theories.number_theory.primes`, which causes a problem.

We can either include `theories` back to `lean.js` or modify the part in chapter 4 not to use `theories.number_theory.primes`. What would be a good solution?

FYI, now the size of `lean.js` is around 13MB without `theories`. When we include `theories`, it's around 15MB.

**Comment by avigad** [comment]
Ah, I see. I included that proof because it is a nice illustration of the proof language. It does not seem to me to be worth it to include all of `theories` just for that example, though.

Some options:
- move primes to data.nat. (I am not crazy about that; I think it is most natural in theories\number_theory.)
- include only theories.number_theory.primes
- declare the necessary facts as axioms in the header (suppressed, with comments explaining the move when users press "Try it yourself"
- use another example

@leodemoura  what do you think?

**Comment by leodemoura** [comment]
@soonhokong and @avigad There is another motivation for not having `primes.lean` in the web version.
The file does not compile after we erase the proofs. We use `dec_trivial` in a few places. Here is an example:
https://github.com/leanprover/lean/blob/master/library/theories/number_theory/primes.lean#L52

`primes` decidability depends on well founded recursion, and we need proofs for them to compute inside of the Lean kernel.

To support this kind of file, we have to change how we generate the .olean files for the web version.
We have to do in two steps: first, we compile everything with the proofs; then we load all .olean, erase the proofs and create a new big .olean file.

For now, we should remove the example.

**Comment by soonhokong** [comment]
> The file does not compile after we erase the proofs.

Right..

> For now, we should remove the example.

@avigad, let me first comment out the last paragraph of chapter 4 and the following lean code block. When you re-visit chapter 4, please feel free to revise them or delete them.

**Comment by avigad** [comment]
Sounds good. I'll think about how to replace it.
