### ISSUE TITLE
Confusing text on “suppose” vs. “assume” in Section 4.6

### ISSUE THREAD

**Issue by spl** [leanprover/tutorial#162]
I found the following text rather confusing in Section 4.6 More on the Proof Language:

> Using the keyword `assume` for this purpose would result in a syntactic ambiguity, since the expression `assume h k` could mean "assume `h` and assume `k`", leaving Lean to infer the relevant hypotheses from the context, or "assume proposition `h k` without a label". Using `suppose` avoids the problem. As with the anonymous `have`, the assumption can also be invoked by enclosing the assertion in backticks later in the proof.

First, it wasn't clear what “this” was referring to in the first sentence. Only later did I realize that it was referring to the _following_ example code (I think). If so, then that fact should be made more clear, since “this” usually refers to something already referenced.

Second, I don't understand how `assume` results in syntactic ambiguity. Either (1) you are talking about something that you haven't introduced yet (one can assume proposition `h k` without a label?), or (2) you are comparing apples to oranges by comparing `suppose` with hypotheses to `assume` without hypotheses, or (3) there is something else or some combination of the above going on.

**Comment by avigad** [comment]
You are right, it is a lousy explanation. I'll fix it. The issue is that there is an asymmetry: you can write both
```lean
have H : x = 0, ...
```
and
```lean
have x = 0, ...
```
but for assumptions, you have to write either
```lean
assume H : x = 0
```
or
```
suppose x = 0
```
I was trying to explain why we cannot allow anonymous "assume". The problem is Lean also lets you write
```lean
assume H, ...
```
to introduce the hypothesis with label `H`, and let Lean infer the proposition that is being asumed. I is equivalent to
```lean
assume H : _, ...
```
But if we were to allow anonymous `assume`, there would be ambiguity with `assume H`: it could mean, infer the proposition that we are assuming, and label it `H`, or assume the proposition `H`, with implicit label `this`.

Does that make sense?

**Comment by spl** [comment]
> Does that make sense?

Yep. Thanks!

**Comment by spl** [comment]
Actually, I think it's important that this is a question of language design rather than user usage. In other words, you explained here why the language designer would not allow for an anonymous `assume`. But from a tutorial perspective, it should perhaps be more of a “Hey, watch out for this potential syntax gotcha!”

(It just occurred to me that one shouldn't just assume one can be anonymous with `assume`. Punny!)
