### ISSUE TITLE
Making auxiliary facts visible: have, assert, using

### ISSUE THREAD

**Issue by spl** [leanprover/tutorial#173]
In Section 8.6 Making Auxiliary Facts Visible, there is the following example:

``` lean
example (p q r : Prop) : p ∧ q ∧ r → q ∧ p :=
assume Hpqr : p ∧ q ∧ r,
assert Hp   : p,     from and.elim_left Hpqr,
have   Hqr  : q ∧ r, from and.elim_right Hpqr,
assert Hq   : q,     from and.elim_left Hqr,
proof
  -- Hp and Hq are visible here,
  -- Hqr is not because we used "have".
  and.intro Hq Hp
qed
```

The text introduces “visible” with:

> Given the term `have H : p, from s, t`, by default, the hypothesis `H` is not "visible" by automated procedures and tactics used to construct t.

I'm not yet sure what “visible” means exactly. The text also seems to use “available” interchangeably with “visible.” I thought it might mean something like “in scope.” So when I changed `assert` to `have` in the above example, I expected a complaint from Lean. But I didn't get one.

Likewise, removing `using Hp` from the following also did not produce an error:

``` lean
example (p q r : Prop) : p ∧ q ∧ r → q ∧ p :=
assume Hpqr : p ∧ q ∧ r,
have   Hp   : p,      from and.elim_left Hpqr,
have   Hqr  : q ∧ r,  from and.elim_right Hpqr,
assert Hq   : q,      from and.elim_left Hqr,
show q ∧ p, using Hp, from
proof
  -- Hp is visible here because of =using Hp=
  and.intro Hq Hp
qed
```

What should I expect to see when making these changes (renaming `assert` to `have`, removing `using`, etc.)? What do “visible” and “available” mean, assuming my intuition is incorrect?

**Comment by avigad** [comment]
The problem is simply that the tutorial is out of date: Leo changed the semantics of `proof ... qed` so that now all the hypotheses are put in the context by default.

We still need to use `assert` and `using`, etc., for tactics, and also for unusual situations where the elaborator needs to find them to infer an implicit parameter, as described in Chapter 12.

Probably the best thing to do is to remove the false statements and move the discussion to Chapter 11 (tactics). I will sort this out soon.

**Comment by spl** [comment]
Ah, that makes sense. Thanks for the explanation.
