### ISSUE TITLE
blackboard bold N for nat does not appear in the pdf file

### ISSUE THREAD

**Issue by avigad** [leanprover/tutorial#23]
For example, in Sections 4.2 and 6.2.

(Another issue is that we should be more consistent about using "nat" or "IN". At some point, I'll change them to the blackboard bold N.)

**Comment by soonhokong** [comment]
We're using [Unixode](https://github.com/olivierverdier/Unixode) package to convert a unicode character to a latex markup. For instance, unicode charater 'α' is converted to '\alpha' thanks to this package.

Problem was that it didn't have an entry for "blackboard bold N". I just added the entry in f76b6c8. I guess that we're missing many other symbols. In case you find some math symbols are not rendered correctly or completely missing, please look up the unixode.sty file (or simply let me know so that I can help).

**Comment by soonhokong** [comment]
Also, when you see a red box in a Lean code block (in PDF), please let me know. Normally, it happens when our syntax highlighting rule has missing symbols. For example, we had red boxes around '⌞', '⌟', and '≡' symbols. I just fixed the problem and created a pull-request to the [main pygment repository](https://bitbucket.org/birkenfeld/pygments-main/pull-request/427/add-missing-operators-for-lean-theorem/diff).

**Comment by soonhokong** [comment]
FYI, Pull-request merged https://bitbucket.org/birkenfeld/pygments-main/pull-request/427
