### ISSUE TITLE
Can structure type parameter be a variable or a lambda redex?

### ISSUE THREAD

**Issue by htzh** [leanprover/tutorial#99]
I have trouble type checking the following:
```
variable {A : Type}
variable [s : group A]
include s
definition lmul_by (a : A) := λ x, a * x
definition rmul_by (a : A) := λ x, x * a
definition lcoset H (a : A) : set A := λ x, H (a⁻¹ * x)
definition rcoset H (a : A) : set A := λ x, H (x * a⁻¹)
lemma lmul_maps_to_lcoset : ∀ {{H a}}, maps_to (lmul_by a) H (lcoset H a) :=
      begin
        intro H, intro a,
        rewrite ↑maps_to,
        intro x,
        intro P1,
        --rewrite [↑mem, ↑lcoset, ↑lmul_by],
        exact (eq.subst (eq.symm (inv_mul_cancel_left a x)) P1)
      end
definition lcoset_map a (H : set A)
           := {|map H (lcoset H a), func := lmul_by a,  mapsto := lmul_maps_to_lcoset H a|}
check λ a H, {|map H (lcoset H a), func := lmul_by a,  mapsto := lmul_maps_to_lcoset H a|} 
```
In Emacs I just get a mysterious ```fuction expected at ?M_1```. I don't know if this is because I am not matching the type signature of map or in general lambda redexes can not be used to parameterize structures.

Also is the {| |} notation the only way to explicitly instantiate the type parameters for structures?

**Comment by fpvandoorn** [comment]
I think you misunderstand the `{{}}` notation. They are a special kind of implicit arguments, similar to `{}`. See section "8.2 More on Implicit Arguments" in the tutorial about them. (this section was added recently). If I replace `{{H a}}` in your file by `(H a)`, then your file compiles.

The error message is indeed not very helpful. The problem was what you applied `lmul_maps_to_lcoset` to arguments, while it doesn't expect explicit arguments (it only has 2 implicit arguments). I don't know why the error message says `?M_1` instead of `lmul_maps_to_lcoset`.

(For future issues: please also include the lines where you import files and open namespaces.)

**Comment by htzh** [comment]
I see. Thanks! The following appears to work as well (without removing {{}}):
```
check λ a H, {|map H (lcoset H a), func := lmul_by a,  mapsto := @lmul_maps_to_lcoset _ _ H a|}
```
Another previous question of mine should be edited to read:
```
Also is the {| |} notation the only way to explicitly instantiate the type parameters for structures?
```
I think the answer is that the mk function can be used as well.
